services:
  ai-draw-studio:
    image: ai-draw-studio:latest
    build:
      context: .
    container_name: ai-draw-studio
    pull_policy: never
    ports:
      - "6001:6001"
    env_file:
      - .env.local
    restart: unless-stopped
